export const containerRecetas = document.querySelector("#recetas-container")
export const listaRecetas = document.querySelector("#lista-recetas")
export const btnCalcularMasa = document.querySelector("#calcular-masa")
export const hojaImpresionContainer = document.querySelector("#hoja-impresion-container")
export const inputCantidadMasa = document.getElementById("masaCantidad")
export const DescripcionProducto = document.querySelector("#masa-section")
